### ISSUE TITLE
Please add genome option to the pipeline

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/sc-atacseq-smk-pipeline#2]

**Comment by dievsky** [comment]
Unfortunately, the mappability blacklist removal step requires a hardcoded path to the specific blacklist.
We could outsource the blacklist download to the user, though, mentioning it in the readme.

**Comment by dievsky** [comment]
For example, for `hg19` it's http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeMapability/wgEncodeDacMapabilityConsensusExcludable.bed.gz , and for `mm9` it's http://mitra.stanford.edu/kundaje/akundaje/release/blacklists/mm9-mouse/mm9-blacklist.bed.gz .

**Comment by dievsky** [comment]
Oh, and the `clean_bams` rule requires a list of "regular" chromosomes, which would also vary with the genome build.
So, the simplest way around this is:
- pass the configuration properties via YAML file, since there too many now;
- pass the genome build, path to blacklist and the list of regular chromosomes via config;
- add a sample config file for user's convenience.

**Comment by dievsky** [comment]
Moved the configuration properties to `config.yaml`, provided an example of config and instructions on how to edit it.
